/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/l0calh0st/simple-router/pkg/apis/simplerouter.l0calh0st.cn/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSimples implements SimpleInterface
type FakeSimples struct {
	Fake *FakeSimplerouterV1alpha1
	ns   string
}

var simplesResource = schema.GroupVersionResource{Group: "simplerouter.l0calh0st.cn", Version: "v1alpha1", Resource: "simples"}

var simplesKind = schema.GroupVersionKind{Group: "simplerouter.l0calh0st.cn", Version: "v1alpha1", Kind: "Simple"}

// Get takes name of the simple, and returns the corresponding simple object, and an error if there is any.
func (c *FakeSimples) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Simple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(simplesResource, c.ns, name), &v1alpha1.Simple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Simple), err
}

// List takes label and field selectors, and returns the list of Simples that match those selectors.
func (c *FakeSimples) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SimpleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(simplesResource, simplesKind, c.ns, opts), &v1alpha1.SimpleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SimpleList{ListMeta: obj.(*v1alpha1.SimpleList).ListMeta}
	for _, item := range obj.(*v1alpha1.SimpleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested simples.
func (c *FakeSimples) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(simplesResource, c.ns, opts))

}

// Create takes the representation of a simple and creates it.  Returns the server's representation of the simple, and an error, if there is any.
func (c *FakeSimples) Create(ctx context.Context, simple *v1alpha1.Simple, opts v1.CreateOptions) (result *v1alpha1.Simple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(simplesResource, c.ns, simple), &v1alpha1.Simple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Simple), err
}

// Update takes the representation of a simple and updates it. Returns the server's representation of the simple, and an error, if there is any.
func (c *FakeSimples) Update(ctx context.Context, simple *v1alpha1.Simple, opts v1.UpdateOptions) (result *v1alpha1.Simple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(simplesResource, c.ns, simple), &v1alpha1.Simple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Simple), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSimples) UpdateStatus(ctx context.Context, simple *v1alpha1.Simple, opts v1.UpdateOptions) (*v1alpha1.Simple, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(simplesResource, "status", c.ns, simple), &v1alpha1.Simple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Simple), err
}

// Delete takes name of the simple and deletes it. Returns an error if one occurs.
func (c *FakeSimples) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(simplesResource, c.ns, name, opts), &v1alpha1.Simple{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSimples) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(simplesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SimpleList{})
	return err
}

// Patch applies the patch and returns the patched simple.
func (c *FakeSimples) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Simple, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(simplesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Simple{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Simple), err
}
